Repository elastic/elasticsearch-js, pull requests merged in 2019-10, with the labels that each got.

#985 [DOCS] Fine-tunes the Node.js client introduction
  docs/introduction.asciidoc
Labels: documentation

#986 [7.x] [DOCS] Fine-tunes the Node.js client introduction
  docs/introduction.asciidoc
Labels: documentation, v7.x

#988 [DOCS] Fine-tunes the Node.js client usage section
  docs/usage.asciidoc
Labels: documentation

#989 [7.x] [DOCS] Fine-tunes the Node.js client usage section
  docs/usage.asciidoc
Labels: documentation, v7.x

#995 Move back to jjbb
  .ci/Jenkinsfile
  .ci/jobs/elastic+elasticsearch-js+5.x.yml
  .ci/jobs/elastic+elasticsearch-js+6.x.yml
  .ci/jobs/elastic+elasticsearch-js+7.x.yml
  .ci/jobs/elastic+elasticsearch-js+master.yml
  .ci/jobs/elastic+elasticsearch-js+mbp.yml
  .ci/jobs/elastic+elasticsearch-js+pull-request.yml
Labels: tests

#996 New CI configuration
  .ci/docker-compose.yml
  .ci/run-elasticsearch.sh
  .ci/run-tests
  .ci/test-matrix.yml
  README.md
Labels: tests

#998 [DOCS] Fine-tunes the Node.js client configuration section
  docs/configuration.asciidoc
Labels: documentation, v8.x

#999 [7.x][DOCS] Fine-tunes the Node.js client configuration section
  docs/configuration.asciidoc
Labels: documentation, v7.x
