Repository elastic/elasticsearch-js, pull requests merged in 2019-03, with the labels that each got.

#772 Platinum integration test
  .ci/certs/ca.crt
  .ci/certs/testnode.crt
  .ci/certs/testnode.key
  .ci/docker-compose.yml
  .ci/run-tests
  api/api/ml.delete_calendar_event.js
  api/api/ml.delete_calendar_job.js
  api/api/ml.delete_forecast.js
  api/api/ml.delete_model_snapshot.js
  api/api/ml.find_file_structure.js
  api/api/ml.get_buckets.js
  api/api/ml.get_model_snapshots.js
  api/api/ml.put_calendar_job.js
  api/api/ml.revert_model_snapshot.js
  api/api/ml.update_model_snapshot.js
  api/api/security.get_privileges.js
  api/api/xpack.watcher.ack_watch.js
  lib/Transport.js
  package.json
  scripts/es-docker-platinum.sh
  scripts/utils/generate.js
  test/integration/helper.js
  test/integration/index.js
  test/integration/test-runner.js
Labels: next

#745 WIP: benchmarks
  .gitignore
  package.json
  scripts/es-docker.sh
  scripts/kibana-docker.sh
  test/benchmarks/basic.bench.js
  test/benchmarks/macro/complex.bench.js
  test/benchmarks/macro/simple.bench.js
  test/benchmarks/micro/basic.bench.js
  test/benchmarks/suite.js
Labels: next, tests

#777 Added codecov
  .ci/docker-compose.yml
  .ci/jobs/defaults.yml
  .ci/run-tests
  .codecov.yml
  package.json
Labels: tests

#783 Feat: Support bundlers
  api/index.js
  scripts/utils/genMain.js
Labels: backport-5.x, backport-6.x, backport-7.x, bugfix

#784 Inspect Connection
  lib/Connection.d.ts
  lib/Connection.js
  test/unit/connection.test.js
Labels: backport-5.x, backport-6.x, backport-7.x, enhancement

#786 CI config
  .ci/.dockerignore
  .ci/Dockerfile
  .ci/run-tests
  .ci/test-matrix.yml
  .dockerignore
Labels: tests

#791 Doc updates
  docs/authentication.asciidoc
  docs/breaking-changes.asciidoc
  docs/child.asciidoc
  docs/configuration.asciidoc
  docs/examples/asStream.asciidoc
  docs/examples/bulk.asciidoc
  docs/examples/exists.asciidoc
  docs/examples/get.asciidoc
  docs/examples/ignore.asciidoc
  docs/examples/index.asciidoc
  docs/examples/msearch.asciidoc
  docs/examples/scroll.asciidoc
  docs/examples/search.asciidoc
  docs/examples/suggest.asciidoc
  docs/examples/transport.request.asciidoc
  docs/examples/typescript.asciidoc
  docs/extend.asciidoc
  docs/index.asciidoc
  docs/introduction.asciidoc
  docs/reference.asciidoc
  docs/typescript.asciidoc
  docs/usage.asciidoc
  scripts/utils/generateDocs.js
Labels: backport-5.x, backport-6.x, backport-7.x, documentation

#793 Make legacy docs asciidoctor compatible
  docs/api_param_types.asciidoc
  docs/configuration.asciidoc
  scripts/generate/templates/configuration_docs.tmpl
Labels: documentation, legacy

#794 Updated CONTRIBUTING.md
  CONTRIBUTING.md
  package.json
  scripts/generate.js
  scripts/utils/generateApis.js
  scripts/utils/generateMain.js
  scripts/utils/index.js
Labels: documentation, enhancement

#796 Fix docs
  docs/authentication.asciidoc
  docs/breaking-changes.asciidoc
  docs/child.asciidoc
  docs/configuration.asciidoc
  docs/extend.asciidoc
  docs/introduction.asciidoc
  docs/reference.asciidoc
  docs/typescript.asciidoc
  docs/usage.asciidoc
  scripts/utils/generateDocs.js
Labels: documentation

#797 Docs: Fix link in changelog
  docs/changelog.asciidoc
Labels: documentation, legacy

#799 Docs: Fix the API reference
  docs/index.asciidoc
  docs/reference.asciidoc
  scripts/utils/generateDocs.js
Labels: documentation

#800 Docs: Handle more funny cases from ES api spec
  scripts/utils/generateDocs.js
Labels: documentation

#801 Docs: Fix ingest doc links
  scripts/utils/generateDocs.js
Labels: documentation
