Repository elastic/elasticsearch-js, pull requests merged in 2019-07, with the labels that each got.

#887 Remove auth data from inspect and toJSON in connection class
  lib/Connection.js
  test/unit/connection.test.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, bugfix

#894 Updated travis configuration
  .travis.yml
  test/behavior/resurrect.test.js
Labels: tests

#859 Improve integration test
  .ci/jobs/defaults.yml
  .gitignore
  package.json
  scripts/es-docker-platinum.sh
  scripts/es-docker.sh
  test/integration/helper.js
  test/integration/index.js
  test/integration/test-runner.js
Labels: tests, todo

#903 [DOCS] Fix broken links for ES API docs move
  api/api/clear_scroll.js
  api/api/scroll.js
Labels: 8.x, backport-7.x

#910 Added support for arbitrary_key in integration test.
  test/integration/test-runner.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, tests

#909 Improve README
  README.md
  docs/index.asciidoc
  docs/introduction.asciidoc
Labels: documentation

#912 Fix typo in comments
  docs/typescript.asciidoc
  test/types/index.ts
Labels: documentation

#908 Improve authentication handling
  docs/authentication.asciidoc
  docs/configuration.asciidoc
  index.d.ts
  index.js
  lib/Connection.d.ts
  lib/Connection.js
  lib/ConnectionPool.d.ts
  lib/ConnectionPool.js
  test/types/index.ts
  test/unit/client.test.js
  test/unit/connection-pool.test.js
  test/unit/connection.test.js
Labels: semver-minor, v6.x, v7.3, v8.x

#914 fix(Typings): sniffInterval can also be boolean
  index.d.ts
Labels: bugfix, typescript, v5.x, v6.x, v7.x, v8.x

#911 Added job configuration for Jenkins pipelines
  .ci/jobs/elastic+elasticsearch-js+jenkins-pipelines.yml
Labels: tests

#919 Updated automatically the main typings file with the generated types
  .gitignore
  index.d.ts
  scripts/generate.js
  scripts/utils/generateMain.js
Labels: internals

#920 Better reference code examples
  docs/reference.asciidoc
  scripts/utils/generateDocs.js
Labels: documentation

#924 [wip] Move from docker agent to labels
  Jenkinsfile
Labels: tests
