Repository elastic/elasticsearch-js, pull requests merged in 2019-12, with the labels that each got.

#997 X-Opaque-Id support
  docs/configuration.asciidoc
  docs/observability.asciidoc
  index.d.ts
  index.js
  lib/Transport.d.ts
  lib/Transport.js
  test/unit/client.test.js
Labels: semver-minor, v7.x, v8.x

#1012 [DOCS] Fine-tunes the Node.Js client breaking changes section
  docs/breaking-changes.asciidoc
Labels: documentation, v8.x

#1013 [7.x][DOCS] Fine-tunes the Node.Js client breaking changes section.
  docs/breaking-changes.asciidoc
Labels: documentation, v7.x

#1019 [DOCS] Added older release notice.
  docs/page_header.html
Labels: documentation, v6.x

#1020 [DOCS] Add EOL notice.
  docs/page_header.html
Labels: documentation, v5.x

#1018 [7.x][DOCS] Fine-tunes the Node.Js client authentication section
  docs/authentication.asciidoc
Labels: documentation, v7.x

#1017 [DOCS] Fine-tunes the Node.Js client authentication section
  docs/authentication.asciidoc
Labels: documentation, v8.x

#1024 Update docs examples
  docs/doc_examples/028f6d6ac2594e20b78b8a8f8cbad49d.asciidoc
  docs/doc_examples/033778305d52746f5ce0a2a922c8e521.asciidoc
  docs/doc_examples/06afce2955f9094d96d27067ebca32e8.asciidoc
  docs/doc_examples/0ac9916f47a2483b89c1416684af322a.asciidoc
  docs/doc_examples/0afaf1cad692e6201aa574c8feb6e622.asciidoc
  docs/doc_examples/162b5b693b713f0bfab1209d59443c46.asciidoc
  docs/doc_examples/1c23507edd7a3c18538b68223378e4ab.asciidoc
  docs/doc_examples/34efeade38445b2834749ced59782e25.asciidoc
  docs/doc_examples/35e8da9410b8432cf4095f2541ad7b1d.asciidoc
  docs/doc_examples/4466d410e06712c63328de4db249e6da.asciidoc
  docs/doc_examples/4646764bf09911fee7d58630c72d3137.asciidoc
  docs/doc_examples/4d46dbb96125b27f46299547de9d8709.asciidoc
  docs/doc_examples/4d56b179242fed59e3d6476f817b6055.asciidoc
  docs/doc_examples/5043b83a89091fa00edb341ddf7ba370.asciidoc
  docs/doc_examples/527324766814561b75aaee853ede49a7.asciidoc
  docs/doc_examples/5d13a71fa7fda73b15111803b1c7cfd3.asciidoc
  docs/doc_examples/5d9d7b84e2fec7ecd832145cbb951cf1.asciidoc
  docs/doc_examples/6138d6919f3cbaaf61e1092f817d295c.asciidoc
  docs/doc_examples/6a4679531e64c492fce16dc12de6dcb0.asciidoc
  docs/doc_examples/71b5b2ba9557d0f296ff2de91727d2f6.asciidoc
  docs/doc_examples/774d715155cd13713e6e327adf6ce328.asciidoc
  docs/doc_examples/7f28f8ae8fcdbd807dadde0b5b007a6d.asciidoc
  docs/doc_examples/7f56755fb6c42f7e6203339a6d0cb6e6.asciidoc
  docs/doc_examples/93f1bdd72e79827dcf9a34efa02fd977.asciidoc
  docs/doc_examples/97bcd92ef148312d41e69f0d18284327.asciidoc
  docs/doc_examples/98b121bf47cebd85671a2cb519688d28.asciidoc
  docs/doc_examples/9a8995fd31351045d99c78e40444c8ea.asciidoc
  docs/doc_examples/a49169b4622918992411fab4ec48191b.asciidoc
  docs/doc_examples/b9c5d7ca6ca9c6f747201f45337a4abf.asciidoc
  docs/doc_examples/cd5bc5bf7cd58d7b1492c9c298b345f6.asciidoc
  docs/doc_examples/d50a3835bf5795ac73e58906a3413544.asciidoc
  docs/doc_examples/dc15e2373e5ecbe09b4ea0858eb63d47.asciidoc
  docs/doc_examples/dfef545b1e2c247bafd1347e8e807ac1.asciidoc
  docs/doc_examples/e0d6e02b998bdea99c9c08dcc3630c5e.asciidoc
  docs/doc_examples/e5d2172b524332196cac0f031c043659.asciidoc
  docs/doc_examples/f085fb032dae56a3b104ab874eaea2ad.asciidoc
  docs/doc_examples/f29a28fffa7ec604a33a838f48f7ea79.asciidoc
  docs/doc_examples/f70a54cd9a9f4811bf962e469f2ca2ea.asciidoc
  docs/doc_examples/fa2fe60f570bd930d2891778c6efbfe6.asciidoc
  docs/doc_examples/fa88f6f5a7d728ec4f1d05244228cb09.asciidoc
  docs/doc_examples/fabe14480624a99e8ee42c7338672058.asciidoc
  scripts/generate-docs-examples.js
Labels: documentation, v8.x

#980 Docs: Return super in example Transport subclass
  docs/configuration.asciidoc
Labels: documentation
