Repository elastic/elasticsearch-js, pull requests merged in 2019-06, with the labels that each got.

#870 Docs: added missing configuration options
  docs/configuration.asciidoc
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, documentation

#875 API generation
  api/api/count.js
  api/api/create.js
  api/api/delete.js
  api/api/delete_by_query.js
  api/api/exists.js
  api/api/exists_source.js
  api/api/explain.js
  api/api/get.js
  api/api/get_source.js
  api/api/index.js
  api/api/ml.find_file_structure.js
  api/api/msearch.js
  api/api/mtermvectors.js
  api/api/reindex.js
  api/api/termvectors.js
  api/api/update.js
  api/api/update_by_query.js
  api/requestParams.d.ts
  docs/reference.asciidoc
Labels: 8.x

#877 [DOCS] Fixes typo
  docs/examples/typescript.asciidoc
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, documentation

#880 Added cloud configuration example
  docs/configuration.asciidoc
Labels: 7.x, backport-5.x, backport-6.x, backport-8.x, documentation

#883 Support branch for code generation
  scripts/generate.js
  scripts/utils/clone-es.js
Labels: 7.x, backport-5.x, backport-6.x

#882 Updated type definitions
  index.d.ts
  lib/Connection.d.ts
  test/types/index.ts
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, bugfix, typescript
