Repository elastic/elasticsearch-js, pull requests merged in 2019-05, with the labels that each got.

#835 Updated installation instructions
  docs/introduction.asciidoc
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, documentation

#837 Better handling of hostname/ip:port format
  lib/ConnectionPool.js
  test/unit/connection-pool.test.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, enhancement

#807 Added User-Agent header
  lib/Transport.js
  test/unit/transport.test.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, discussion

#840 Updated installation instructions
  README.md
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, documentation

#842 Fix 841
  index.d.ts
  test/types/index.ts
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, bugfix, typescript

#845 Fix 843
  lib/Connection.js
  test/unit/connection.test.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, bugfix

#846 Fix #803
  lib/Connection.d.ts
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, bugfix, typescript

#849 Added toJSON method to Connection class
  lib/Connection.d.ts
  lib/Connection.js
  test/unit/connection.test.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, enhancement

#854 missing comma
  docs/configuration.asciidoc
Labels: 7.x, backport-5.x, backport-6.x, backport-8.x, documentation

#851 Patch deprecated parameters
  api/api/bulk.js
  api/api/delete_by_query.js
  api/api/exists.js
  api/api/exists_source.js
  api/api/explain.js
  api/api/get.js
  api/api/get_source.js
  api/api/mget.js
  api/api/msearch.js
  api/api/msearch_template.js
  api/api/mtermvectors.js
  api/api/search.js
  api/api/search_template.js
  api/api/termvectors.js
  api/api/update.js
  api/api/update_by_query.js
  api/requestParams.d.ts
  docs/reference.asciidoc
  scripts/generate.js
  scripts/utils/generateApis.js
  scripts/utils/generateRequestTypes.js
  scripts/utils/patch.json
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, enhancement

#858 Support for non-friendly chars in url username and password
  lib/Connection.js
  lib/ConnectionPool.js
  test/unit/connection-pool.test.js
  test/unit/connection.test.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, bugfix
