Repository elastic/elasticsearch-js, pull requests merged in 2019-09, with the labels that each got.

#945 Updated API reference doc
  docs/reference.asciidoc
  scripts/utils/generateDocs.js
Labels: bugfix, documentation

#959 Fix inaccurate description sniffEndpoint
  docs/configuration.asciidoc
Labels: documentation

#967 Fix issue; node roles are defaulting to true when undefined (false) breaking usage of nodeFilter option
  lib/pool/BaseConnectionPool.js
  test/unit/connection-pool.test.js
Labels: bugfix, v5.x, v6.x, v7.x, v8.x

#972 [DOCS] Update docs for 'synced flush' and 'SLM' APIs
  api/api/indices.flush_synced.js
  api/api/slm.get_stats.js
  docs/reference.asciidoc
  index.d.ts
Labels: documentation, v7.x, v8.x

#976 [7.x] [DOCS] Update docs for 'synced flush' and 'SLM' APIs (#972)
  api/api/indices.flush_synced.js
  docs/reference.asciidoc
Labels: documentation, v7.x
