Repository elastic/elasticsearch-js, pull requests merged in 2019-04, with the labels that each got.

#804 Support for publish_address as hostname/ip:port
  lib/ConnectionPool.d.ts
  lib/ConnectionPool.js
  lib/Transport.js
  test/behavior/sniff.test.js
  test/unit/connection-pool.test.js
  test/utils/buildCluster.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x

#810 Custom http agent support
  docs/configuration.asciidoc
  index.d.ts
  lib/Connection.d.ts
  lib/Connection.js
  test/unit/connection.test.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x

#813 Improve typings
  api/api/data_frame.get_data_frame_transform_stats.js
  api/requestParams.d.ts
  docs/reference.asciidoc
  docs/typescript.asciidoc
  lib/Transport.d.ts
  scripts/utils/generateRequestTypes.js
  test/types/index.ts
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, documentation, typescript

#806 Fix a typo in usage example
  docs/usage.asciidoc
Labels: documentation

#818 Drop Node.js v6 support
  .ci/test-matrix.yml
  .npmignore
  .travis.yml
  README.md
  docs/breaking-changes.asciidoc
  docs/introduction.asciidoc
  package.json
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x

#819 Updated typings
  index.d.ts
  lib/Transport.d.ts
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, typescript

#820 Use Elasticsearch 7.0.0
  .ci/test-matrix.yml
  .travis.yml
  scripts/es-docker-platinum.sh
  scripts/es-docker.sh
  scripts/kibana-docker.sh
Labels: 7.x

#822 Update RequestEvent to use parameterized type T
  lib/Transport.d.ts
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x

#828 Support for deprecated paths
  api/api/clear_scroll.js
  api/api/count.js
  api/api/create.js
  api/api/delete.js
  api/api/delete_by_query.js
  api/api/exists.js
  api/api/exists_source.js
  api/api/explain.js
  api/api/get.js
  api/api/get_source.js
  api/api/graph.explore.js
  api/api/index.js
  api/api/indices.get_field_mapping.js
  api/api/indices.get_mapping.js
  api/api/indices.put_mapping.js
  api/api/indices.validate_query.js
  api/api/mget.js
  api/api/monitoring.bulk.js
  api/api/msearch.js
  api/api/msearch_template.js
  api/api/mtermvectors.js
  api/api/nodes.hot_threads.js
  api/api/rollup.rollup_search.js
  api/api/scroll.js
  api/api/search.js
  api/api/search_template.js
  api/api/termvectors.js
  api/api/update.js
  api/api/update_by_query.js
  scripts/utils/generateApis.js
  test/integration/index.js
Labels: 8.x, backport-7.x

#831 Updated .travis.yml
  .travis.yml
Labels: tests

#832 Node v12 and bumped dependencies
  .ci/test-matrix.yml
  .travis.yml
  package.json
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, tests

#833 Fix resurrect timeout formula
  lib/ConnectionPool.js
  test/behavior/resurrect.test.js
Labels: 8.x, backport-5.x, backport-6.x, backport-7.x, bugfix
