Repository elastic/elasticsearch-js, pull requests merged in 2019-11, with the labels that each got.

#1007 [7.x][DOCS] Fine-tunes the Node.js client API reference section
  docs/reference.asciidoc
Labels: documentation, v7.x

#1006 [DOCS] Fine-tunes the Node.js client API reference section
  docs/reference.asciidoc
Labels: documentation, v8.x

#1011 Added doc examples
  docs/doc_examples/048d8abd42d094bbdcf4452a58ccb35b.asciidoc
  docs/doc_examples/0ba0b2db24852abccb7c0fc1098d566e.asciidoc
  docs/doc_examples/0ce3606f1dba490eef83c4317b315b62.asciidoc
  docs/doc_examples/138ccd89f72aa7502dd9578403dcc589.asciidoc
  docs/doc_examples/1d65cb6d055c46a1bde809687d835b71.asciidoc
  docs/doc_examples/1f336ecc62480c1d56351cc2f82d0d08.asciidoc
  docs/doc_examples/231aa0bb39c35fe199d28fe0e4a62b2e.asciidoc
  docs/doc_examples/2468ab381257d759d8a88af1141f6f9c.asciidoc
  docs/doc_examples/251ea12c1248385ab409906ac64d9ee9.asciidoc
  docs/doc_examples/28aad2c5942bfb221c2bf1bbdc01658e.asciidoc
  docs/doc_examples/311c4b632a29b9ead63b02d01f10096b.asciidoc
  docs/doc_examples/36818c6d9f434d387819c30bd9addb14.asciidoc
  docs/doc_examples/3d1ff6097e2359f927c88c2ccdb36252.asciidoc
  docs/doc_examples/3f3b3e207f79303ce6f86e03e928e062.asciidoc
  docs/doc_examples/47b5ff897f26e9c943cee5c06034181d.asciidoc
  docs/doc_examples/47bb632c6091ad0cd94bc660bdd309a5.asciidoc
  docs/doc_examples/4b90feb9d5d3dbfce424dac0341320b7.asciidoc
  docs/doc_examples/506844befdc5691d835771bcbb1c1a60.asciidoc
  docs/doc_examples/58b5003c0a53a39bf509aa3797aad471.asciidoc
  docs/doc_examples/5eabcdbf61bfcb484dc694f25c2bba36.asciidoc
  docs/doc_examples/609260ad1d5998be2ca09ff1fe237efa.asciidoc
  docs/doc_examples/60ee33f3acfdd0fe6f288ac77312c780.asciidoc
  docs/doc_examples/625dc94df1f9affb49a082fd99d41620.asciidoc
  docs/doc_examples/645796e8047967ca4a7635a22a876f4c.asciidoc
  docs/doc_examples/69a7be47f85138b10437113ab2f0d72d.asciidoc
  docs/doc_examples/6f21a878fee3b43c5332b81aaddbeac7.asciidoc
  docs/doc_examples/710c7871f20f176d51209b1574b0d61b.asciidoc
  docs/doc_examples/71ba9033107882f61cdc3b32fc73568d.asciidoc
  docs/doc_examples/745f9b8cdb8e91073f6e520e1d9f8c05.asciidoc
  docs/doc_examples/804a97ff4d0613e6568e4efb19c52021.asciidoc
  docs/doc_examples/89a8ac1509936acc272fc2d72907bc45.asciidoc
  docs/doc_examples/8fdf2344c4fb3de6902ad7c5735270df.asciidoc
  docs/doc_examples/913770050ebbf3b9b549a899bc11060a.asciidoc
  docs/doc_examples/98234499cfec70487cec5d013e976a84.asciidoc
  docs/doc_examples/99a52be903945b17e734a1d02a57e958.asciidoc
  docs/doc_examples/a2a25aad1fea9a541b52ac613c78fb64.asciidoc
  docs/doc_examples/ad6ea0c1e46712aa1fd6d3bfa0ec979e.asciidoc
  docs/doc_examples/b918d6b798da673a33e49b94f61dcdc0.asciidoc
  docs/doc_examples/bb143628fd04070683eeeadc9406d9cc.asciidoc
  docs/doc_examples/be1bd47393646ac6bbee177d1cdb7738.asciidoc
  docs/doc_examples/bfcd65ab85d684d36a8550080032958d.asciidoc
  docs/doc_examples/c5e5873783246c7b1c01d8464fed72c4.asciidoc
  docs/doc_examples/cd247f267968aa0927bfdad56852f8f5.asciidoc
  docs/doc_examples/cfbaea6f0df045c5d940bbb6a9c69cd8.asciidoc
  docs/doc_examples/d222c6a6ec7a3beca6c97011b0874512.asciidoc
  docs/doc_examples/d718b63cf1b6591a1d59a0cf4fd995eb.asciidoc
  docs/doc_examples/d8b2a88b5eca99d3691ad3cd40266736.asciidoc
  docs/doc_examples/d90a84a24a407731dfc1929ac8327746.asciidoc
  docs/doc_examples/db6cba451ba562abe953d09ad80cc15c.asciidoc
  docs/doc_examples/e17e8852ec3f31781e1364f4dffeb6d0.asciidoc
  docs/doc_examples/f2d68493abd3ca430bd03a7f7f8d18f9.asciidoc
  docs/doc_examples/f32f0c19b42de3b87dd764fe4ca17e7c.asciidoc
  docs/doc_examples/f8cc4b331a19ff4df8e4a490f906ee69.asciidoc
  docs/doc_examples/fbcf5078a6a9e09790553804054c36b3.asciidoc
  docs/doc_examples/fdd38f0d248385a444c777e7acd97846.asciidoc
  docs/doc_examples/feefeb68144002fd1fff57b77b95b85e.asciidoc
  scripts/generate-docs-examples.js
Labels: documentation, enhancement
