Repository elastic/elasticsearch-js, pull requests merged in 2020-06, with the labels that each got.

#1206 Added timeout support in bulk and msearch helpers
  docs/helpers.asciidoc
  lib/Helpers.d.ts
  lib/Helpers.js
  package.json
  test/types/helpers.test-d.ts
  test/unit/helpers/bulk.test.js
  test/unit/helpers/msearch.test.js
Labels: backport 7.x, semver-minor, v8.x

#1212 Fixed types code generation
  scripts/utils/generateRequestTypes.js
Labels: backport 7.x, typescript, v8.x

#1214 Improve helper concurrency
  docs/helpers.asciidoc
  lib/Helpers.js
  test/integration/helpers/msearch.test.js
  test/unit/helpers/msearch.test.js
Labels: backport 7.x, bugfix, documentation, v8.x

#1217 Documentation fixes
  docs/authentication.asciidoc
  docs/breaking-changes.asciidoc
  docs/configuration.asciidoc
  docs/helpers.asciidoc
  docs/usage.asciidoc
Labels: backport 7.x, bugfix, documentation, v8.x

#1221 migrated to FakeTimers
  package.json
  test/behavior/observability.test.js
  test/behavior/resurrect.test.js
  test/behavior/sniff.test.js
  test/unit/transport.test.js
Labels: backport 7.x, tests, v8.x

#1222 improved test coverage
  test/unit/connection.test.js
Labels: backport 7.x, tests, v8.x

#1224 Helpers: avoid allocating new timers
  lib/Helpers.js
  package.json
  test/unit/helpers/msearch.test.js
Labels: backport 7.x, internals, v8.x

#1226 Reorganized test and force 100% code coverage
  .github/workflows/nodejs.yml
  index.js
  lib/Connection.js
  lib/Helpers.js
  lib/Transport.js
  lib/pool/BaseConnectionPool.js
  lib/pool/CloudConnectionPool.js
  lib/pool/ConnectionPool.js
  package.json
  test/acceptance/observability.test.js
  test/acceptance/resurrect.test.js
  test/acceptance/sniff.test.js
  test/unit/client.test.js
  test/unit/connection.test.js
  test/unit/helpers/bulk.test.js
  test/unit/helpers/msearch.test.js
Labels: backport 7.x, tests, v8.x

#1219 Changelog for 7.8
  docs/changelog.asciidoc
Labels: documentation, todo, v7.x

#1231 Added option to run the benchmarks sequentially or concurrently
  test/benchmarks/actions/001_ping.js
  test/benchmarks/actions/002_info.js
  test/benchmarks/actions/003_get.js
  test/benchmarks/actions/004_index.js
  test/benchmarks/actions/005_bulk.js
  test/benchmarks/actions/006_bulk-helper.js
  test/benchmarks/lib.js
  test/benchmarks/run.js
Labels: tests

#1235 ESM support
  index.mjs
  package.json
  test/unit/esm/index.mjs
  test/unit/esm/index.test.js
Labels: backport 7.x, semver-minor, v8.x

#1234 Fix API example usage
  README.md
  docs/introduction.asciidoc
  docs/usage.asciidoc
Labels: backport 5.x, backport 6.x, backport 7.x, bugfix, documentation, v8.x

#1237 Update typescript.asciidoc
  docs/typescript.asciidoc
Labels: backport 7.x, documentation, v8.x
