Repository elastic/elasticsearch-js, pull requests merged in 2020-01, with the labels that each got.

#1032 ClientOptions["cloud"] should have optional auth fields
  index.d.ts
Labels: bugfix, typescript

#1031 Added new examples
  docs/examples/reindex.asciidoc
  docs/examples/sql.asciidoc
  docs/examples/update-by-query.asciidoc
  docs/examples/update.asciidoc
Labels: documentation, todo

#1049 Updated api reference header comment
  scripts/utils/generateDocs.js
Labels: enhancement

#1042 Move to latest .ci script structure
  .ci/run-elasticsearch.sh
  .ci/run-repository.sh
  .ci/run-tests
  .gitignore
Labels: enhancement, tests

#1053 Change TransportRequestOptions.ignore to number[]
  lib/Transport.d.ts
Labels: bugfix, typescript

#1058 [7.x][DOCS] Fine-tunes the Node.Js client child client section
  docs/child.asciidoc
Labels: documentation, v7.x

#1057 [DOCS] Fine-tunes the Node.Js client child client section.
  docs/child.asciidoc
Labels: documentation, v8.x

#1056 [7.x][DOCS] Fine-tunes the Node.Js client observability section
  docs/observability.asciidoc
Labels: documentation, v7.x

#1055 [DOCS] Fine-tunes the Node.Js client observability section.
  docs/observability.asciidoc
Labels: documentation, v8.x

#1008 [DOCS] Updated xrefs to SLM API docs.
  docs/reference.asciidoc
Labels: documentation, todo, v7.x, v8.x

#1005 Improve integration test execution time
  .ci/run-repository.sh
  .ci/run-tests
  package.json
  test/integration/index.js
  test/integration/test-runner.js
Labels: tests, todo

#1061 Renamed log skip function
  test/integration/test-runner.js
Labels: tests

#1065 [7.x][DOCS] Fine-tunes the Node.Js client extend the client section
  docs/extend.asciidoc
Labels: documentation, v7.x

#1064 [DOCS] Fine-tunes the Node.Js client extend the client section
  docs/extend.asciidoc
Labels: documentation, v8.x
