Repository elastic/elasticsearch-js, pull requests merged in 2020-12, with the labels that each got.

#1367 Fix changelog display
  docs/changelog.asciidoc
Labels: documentation, v7.x

#1365 Added new observability events
  docs/observability.asciidoc
  index.d.ts
  index.js
  lib/Transport.js
  test/acceptance/events-order.test.js
  test/unit/events.test.js
Labels: backport 7.x, semver-minor, v8.x

#1375 typo
  docs/examples/bulk.asciidoc
Labels: backport master, documentation, v7.x

#1373 Added x-elastic-client-meta header
  docs/configuration.asciidoc
  index.d.ts
  index.js
  lib/Helpers.js
  lib/Transport.js
  test/unit/client.test.js
  test/unit/helpers/bulk.test.js
  test/unit/helpers/scroll.test.js
Labels: backport 7.x, semver-minor, v8.x

#1376 Fix #1374
  lib/Connection.js
  test/unit/connection.test.js
Labels: backport 7.x, bugfix, v8.x

#1338 Added script for releasing canary package
  .npmignore
  package.json
  scripts/release-canary.js
Labels: backport 7.x, todo, v8.x
