Repository elastic/elasticsearch-js, pull requests merged in 2020-02, with the labels that each got.

#1045 Fix typo in NoLivingConnectionsError
  lib/Transport.js
Labels: bugfix

#1076 Add examples to reference
  docs/examples/index.asciidoc
  docs/examples/sql.query.asciidoc
  docs/examples/update_by_query.asciidoc
  docs/reference.asciidoc
  scripts/utils/generateDocs.js
Labels: documentation

#1079 [7.x][DOCS] Fine-tunes the Node.Js client Typescript and examples sections.
  docs/examples/asStream.asciidoc
  docs/examples/bulk.asciidoc
  docs/examples/get.asciidoc
  docs/examples/msearch.asciidoc
  docs/examples/scroll.asciidoc
  docs/examples/search.asciidoc
  docs/examples/suggest.asciidoc
  docs/examples/transport.request.asciidoc
  docs/examples/typescript.asciidoc
  docs/typescript.asciidoc
Labels: documentation, v7.x

#1078 [DOCS] Fine-tunes the Node.Js client Typescript and examples sections
  docs/examples/asStream.asciidoc
  docs/examples/bulk.asciidoc
  docs/examples/get.asciidoc
  docs/examples/ignore.asciidoc
  docs/examples/msearch.asciidoc
  docs/examples/reindex.asciidoc
  docs/examples/scroll.asciidoc
  docs/examples/search.asciidoc
  docs/examples/sql.query.asciidoc
  docs/examples/suggest.asciidoc
  docs/examples/transport.request.asciidoc
  docs/examples/typescript.asciidoc
  docs/examples/update.asciidoc
  docs/examples/update_by_query.asciidoc
  docs/typescript.asciidoc
Labels: documentation, v8.x

#1080 Skip compression in case of empty string body
  lib/Transport.js
  test/unit/events.test.js
  test/unit/transport.test.js
Labels: bugfix, v5.x, v6.x, v7.x, v8.x

#1083 Added integration test stats
  test/integration/index.js
  test/integration/test-runner.js
Labels: tests

#1085 Update integration test runner
  test/integration/helper.js
  test/integration/test-runner.js
Labels: tests
