Repository elastic/elasticsearch-js, pull requests merged in 2020-03, with the labels that each got.

#1096 [DOCS] Fixes out-dated monitoring links
  docs/reference.asciidoc
  scripts/utils/generateDocs.js
Labels: documentation

#1101 Added new docs examples
  docs/doc_examples/015294a400986295039e52ebc62033be.asciidoc
  docs/doc_examples/09d617863a103c82fb4101e6165ea7fe.asciidoc
  docs/doc_examples/0a958e486ede3f519d48431ab689eded.asciidoc
  docs/doc_examples/0cc991e3f7f8511a34730e154b3c5edc.asciidoc
  docs/doc_examples/1216f8f7367df3aa823012cef310c08a.asciidoc
  docs/doc_examples/1577e6e806b3283c9e99f1596d310754.asciidoc
  docs/doc_examples/1b8655e6ba99fe39933c6eafe78728b7.asciidoc
  docs/doc_examples/1b8caf0a6741126c6d0ad83b56fce290.asciidoc
  docs/doc_examples/1bc731a4df952228af6dfa6b48627332.asciidoc
  docs/doc_examples/2a1de18774f9c68cafa169847832b2bc.asciidoc
  docs/doc_examples/36b2778f23d0955255f52c075c4d213d.asciidoc
  docs/doc_examples/381fced1882ca8337143e6bb180a5715.asciidoc
  docs/doc_examples/38c1d0f6668e9563c0827f839f9fa505.asciidoc
  docs/doc_examples/3ae03ba3b56e5e287953094050766738.asciidoc
  docs/doc_examples/3b04cc894e6a47d57983484010feac0c.asciidoc
  docs/doc_examples/400e89eb46ead8e9c9e40f123fd5e590.asciidoc
  docs/doc_examples/46658f00edc4865dfe472a392374cd0f.asciidoc
  docs/doc_examples/4cd246e5c4c035a2cd4081ae9a3d54e5.asciidoc
  docs/doc_examples/52b2bfbdd78f8283b6f4891c48013237.asciidoc
  docs/doc_examples/58df61acbfb15b8ef0aaa18b81ae98a6.asciidoc
  docs/doc_examples/64b9baa6d7556b960b29698f3383aa31.asciidoc
  docs/doc_examples/68738b4fd0dda177022be45be95b4c84.asciidoc
  docs/doc_examples/6f097c298a7abf4c032c4314920c49c8.asciidoc
  docs/doc_examples/75330ec1305d2beb0e2f34d2195464e2.asciidoc
  docs/doc_examples/764f9884b370cbdc82a1c5c42ed40ff3.asciidoc
  docs/doc_examples/78c96113ae4ed0054e581b17542528a7.asciidoc
  docs/doc_examples/7cac05cb589f1614fd5b8589153bef06.asciidoc
  docs/doc_examples/7f697eb436dfa3c30dfe610d8c32d132.asciidoc
  docs/doc_examples/81c9aa2678d6166a9662ddf2c011a6a5.asciidoc
  docs/doc_examples/8871b8fcb6de4f0c7dff22798fb10fb7.asciidoc
  docs/doc_examples/9166cf38427d5cde5d2ec12a2012b669.asciidoc
  docs/doc_examples/96de5703ba0bd43fd4ac239ec5408542.asciidoc
  docs/doc_examples/973a3ff47fc4ce036ecd9bd363fef9f7.asciidoc
  docs/doc_examples/98aeb275f829b5f7b8eb2147701565ff.asciidoc
  docs/doc_examples/9a4d5e41c52c20635d1fd9c6e13f6c7a.asciidoc
  docs/doc_examples/a80f5db4357bb25b8704d374c18318ed.asciidoc
  docs/doc_examples/ac544eb247a29ca42aab13826ca88561.asciidoc
  docs/doc_examples/b1efa1c51a34dd5ab5511b71a399f5b1.asciidoc
  docs/doc_examples/b5f95bc097a201b29c7200fc8d3d31c1.asciidoc
  docs/doc_examples/cb01106bf524df5e0501d4c655c1aa7b.asciidoc
  docs/doc_examples/cdedd5f33f7e5f7acde561e97bff61de.asciidoc
  docs/doc_examples/cfc37446bd892d1ac42a3c8e8b204e6c.asciidoc
  docs/doc_examples/d0a8a938a2fa913b6fdbc871079a59dd.asciidoc
  docs/doc_examples/d4b4cefba4318caeba7480187faf2b13.asciidoc
  docs/doc_examples/e567e6dbf86300142573c73789c8fce4.asciidoc
  docs/doc_examples/e5f50b31f165462d883ecbff45f74985.asciidoc
  docs/doc_examples/e9c2e15b36372d5281c879d336322b6c.asciidoc
  docs/doc_examples/eb30ba547e4a7b8f54f33ab259aca523.asciidoc
  docs/doc_examples/f9636d7ef1a45be4f36418c875cf6bef.asciidoc
  scripts/generate-docs-examples.js
Labels: documentation

#1104 Migrate to GitHub Actions
  .ci/run-repository.sh
  .github/workflows/backport.yml
  .github/workflows/nodejs.yml
  .travis.yml
  codecov.yml
  package.json
  test/behavior/sniff.test.js
Labels: backport 5.x, backport 6.x, backport 7.x, tests

#1109 typo
  scripts/utils/generateDocs.js
Labels: backport 7.x, documentation, v8.x

#1110 Secure json parsing
  lib/Serializer.js
  package.json
  test/unit/transport.test.js
Labels: backport 5.x, backport 6.x, backport 7.x, bugfix, v8.x

#1115 ApiKey should take precedence over basic auth
  docs/authentication.asciidoc
  lib/Connection.js
  lib/pool/BaseConnectionPool.js
  test/unit/client.test.js
Labels: backport 6.x, backport 7.x, bugfix, v8.x

#1120 [DOCS] Fixes link to cat transforms API
  api/api/transform.cat_transform.js
  docs/reference.asciidoc
Labels: documentation, v8.x

#1100 Add data field in serialization errors
  lib/Serializer.js
  lib/errors.d.ts
  lib/errors.js
  test/unit/errors.test.js
Labels: backport 7.x, enhancement, v8.x

#1119 Refactored type definitions
  api/requestParams.d.ts
  docs/typescript.asciidoc
  index.d.ts
  lib/Connection.d.ts
  lib/Transport.d.ts
  lib/errors.d.ts
  lib/pool/index.d.ts
  package.json
  scripts/generate.js
  scripts/utils/generateApis.js
  scripts/utils/generateMain.js
  scripts/utils/generateRequestTypes.js
  test/types/api-response-body.test-d.ts
  test/types/api-response.test-d.ts
  test/types/client-options.test-d.ts
  test/types/client.test-d.ts
  test/types/connection-pool.test-d.ts
  test/types/connection.test-d.ts
  test/types/errors.test-d.ts
  test/types/index.ts
  test/types/serializer.test-d.ts
  test/types/transport.test-d.ts
  test/types/tsconfig.json
Labels: backport 7.x, semver-minor, typescript, v8.x

#1124 Improve code coverage
  lib/Helpers.js
  lib/Transport.js
  test/unit/helpers/bulk.test.js
  test/unit/helpers/scroll.test.js
  test/unit/helpers/search.test.js
Labels: backport 7.x, tests, v8.x

#1127 Updated Connections handling
  docs/usage.asciidoc
  lib/Transport.js
  lib/errors.js
  lib/pool/ConnectionPool.js
  lib/pool/index.d.ts
  test/unit/connection-pool.test.js
  test/unit/transport.test.js
Labels: backport 7.x, semver-minor, v8.x
