Repository elastic/elasticsearch-js, pull requests merged in 2020-05, with the labels that each got.

#1194 Disable client Helpers in Node.js < 10.
  .github/workflows/nodejs.yml
  docs/helpers.asciidoc
  index.js
  package.json
Labels: backport 7.x, bugfix, v8.x

#1187 Force lowercase in all headers
  lib/Transport.js
  test/unit/client.test.js
  test/unit/helpers/bulk.test.js
  test/unit/transport.test.js
Labels: backport 7.x, bugfix, v8.x

#1197 [DOCS] Fixes Indices component template link in reference docs
  docs/reference.asciidoc
Labels: backport 7.x, documentation, v8.x

#1189 Added new docs examples
  docs/doc_examples/04f5dd677c777bcb15d7d5fa63275fc8.asciidoc
  docs/doc_examples/0bd3923424a20a4ba860b0774b9991b1.asciidoc
  docs/doc_examples/0be2c28ee65384774b1e479b47dc3d92.asciidoc
  docs/doc_examples/1aa91d3d48140d6367b6cabca8737b8f.asciidoc
  docs/doc_examples/1b542e3ea87a742f95641d64dcfb1bdb.asciidoc
  docs/doc_examples/23ab0f1023b1b2cd5cdf2a8f9ccfd57b.asciidoc
  docs/doc_examples/3653567181f43a5f64c74f934aa821c2.asciidoc
  docs/doc_examples/42744a175125df5be0ef77413bf8f608.asciidoc
  docs/doc_examples/427f6b5c5376cbf0f71f242a60ca3d9e.asciidoc
  docs/doc_examples/46c4b0dfb674825f9579203d41e7f404.asciidoc
  docs/doc_examples/4d6997c70a1851f9151443c0d38b532e.asciidoc
  docs/doc_examples/54092c8c646133f5dbbc047990dd458d.asciidoc
  docs/doc_examples/5f210f74725ea0c9265190346edfa246.asciidoc
  docs/doc_examples/618d5f3d35921d8cb7e9ccfbe9a4c3e3.asciidoc
  docs/doc_examples/645136747d37368a14ab34de8bd046c6.asciidoc
  docs/doc_examples/645c4c6e209719d3a4d25b1a629cb23b.asciidoc
  docs/doc_examples/6799d132c1c7ca3970763acde2337ef9.asciidoc
  docs/doc_examples/67bba546d835bca8f31df13e3587c348.asciidoc
  docs/doc_examples/6a81d00f0d73bc5985e76b3cadab645e.asciidoc
  docs/doc_examples/6be70810d6ebd6f09d8a49f9df847765.asciidoc
  docs/doc_examples/7cf71671859be7c1ecf673396db377cd.asciidoc
  docs/doc_examples/8653e76676de5d327201b77512afa3a0.asciidoc
  docs/doc_examples/873fbbc6ab81409058591385fd602736.asciidoc
  docs/doc_examples/8eaf4d5dd4ab1335deefa7749fdbbcc3.asciidoc
  docs/doc_examples/8f0511f8a5cb176ff2afdd4311799a33.asciidoc
  docs/doc_examples/9a26759ccbd338224ecaacf7c49ab08e.asciidoc
  docs/doc_examples/a42f33e15b0995bb4b6058659bfdea85.asciidoc
  docs/doc_examples/a7c15fe6b5779c84ce9a34bf4b2a7ab7.asciidoc
  docs/doc_examples/ad79228630684d950fe9792a768d24c5.asciidoc
  docs/doc_examples/af3fb9fa5691a7b37a6dc2a69ff66e64.asciidoc
  docs/doc_examples/b02e4907c9936c1adc16ccce9d49900d.asciidoc
  docs/doc_examples/b0ec418bf416c62bed602b0a32a6d5f5.asciidoc
  docs/doc_examples/b4392116f2cc57ce8064ccbad30318d5.asciidoc
  docs/doc_examples/b4a0d0ed512dffc10ee53bca2feca49b.asciidoc
  docs/doc_examples/b68c85fe1b0d2f264dc0d1cbf530f319.asciidoc
  docs/doc_examples/ba0b4081c98f3387f76b77847c52ee9a.asciidoc
  docs/doc_examples/bc1ad5cc6d3eab98e3ce01f209ba7094.asciidoc
  docs/doc_examples/bfdad8a928ea30d7cf60d0a0a6bc6e2e.asciidoc
  docs/doc_examples/c48264ec5d9b9679fddd72e5c44425b9.asciidoc
  docs/doc_examples/c612d93e7f682a0d731e385edf9f5d56.asciidoc
  docs/doc_examples/d2153f3100bf12c2de98f14eb86ab061.asciidoc
  docs/doc_examples/d3016e4e8025362ad9a05ee86bb2061f.asciidoc
  docs/doc_examples/de176bc4788ea286fff9e92418a43ea8.asciidoc
  docs/doc_examples/df17f920b0deab3529b98df88b781f55.asciidoc
  docs/doc_examples/dfac8d098b50aa0181161bcd17b38ef4.asciidoc
  docs/doc_examples/e2a042c629429855c3bcaefffb26b7fa.asciidoc
  docs/doc_examples/ec27afee074001b0e4e393611010842b.asciidoc
  docs/doc_examples/ec473de07fe89bcbac1f8e278617fe46.asciidoc
  docs/doc_examples/ef9111c1648d7820925f12e07d1346c5.asciidoc
  docs/doc_examples/f0e21e03a07c8fa0209b0aafdb3791e6.asciidoc
  docs/doc_examples/f6d6889667f56b8f49d2858070571a6b.asciidoc
  docs/doc_examples/fa0f4485cd48f986b7ae8cbb24e331c4.asciidoc
  docs/doc_examples/fe5763d32955e8b65eb3048e97b1580c.asciidoc
  scripts/generate-docs-examples.js
Labels: documentation, v8.x

#1199 Use filter_path for improving the search helpers performances
  docs/helpers.asciidoc
  lib/Helpers.js
  test/unit/helpers/scroll.test.js
  test/unit/helpers/search.test.js
Labels: backport 7.x, semver-minor, v8.x

#1186 Add multi search helper
  docs/helpers.asciidoc
  lib/Helpers.d.ts
  lib/Helpers.js
  test/integration/helpers/msearch.test.js
  test/types/helpers.test-d.ts
  test/unit/helpers/msearch.test.js
Labels: backport 7.x, semver-minor, v8.x

#1207 Update benchmark scripts
  test/benchmarks/actions/005_bulk.js
  test/benchmarks/actions/006_bulk-helper.js
  test/benchmarks/lib.js
  test/benchmarks/run.js
Labels: enhancement
