Repository elastic/elasticsearch-js, pull requests merged in 2020-09, with the labels that each got.

#1284 Helper param fix
  lib/Helpers.js
  test/unit/helpers/scroll.test.js
Labels: backport 7.x, bugfix, v8.x

#1279 Updated run-elasticsearch.sh to retry on docker network failures
  .ci/run-elasticsearch.sh
Labels: backport 7.x, tests, v8.x

#1300 Fix RequestOptions.body type to include null
  lib/Connection.d.ts
Labels: backport 7.x, bugfix, typescript, v8.x

#1296 Fix maxRetries request option handling
  lib/Transport.js
  test/unit/transport.test.js
Labels: backport 7.x, bugfix, v8.x

#1295 Avoid the release of Zalgo
  api/index.js
  lib/Transport.js
  test/unit/api.test.js
  test/unit/transport.test.js
Labels: backport 7.x, bugfix, v8.x

#1305 Integration test: Parse dates as string
  test/integration/index.js
Labels: backport 7.x, tests, v8.x

#1306 Improved cleanup yaml tests
  test/integration/test-runner.js
Labels: backport 7.x, tests, v8.x

#1308 [7.x][DOCS] Fixes link in API reference
  docs/reference.asciidoc
Labels: documentation, v7.x

#1311 Fix rendering of name field in configuration.md
  docs/configuration.asciidoc
Labels: backport master, documentation, v7.x

#1318 Fixed integration test runner
  test/integration/index.js
Labels: backport 7.x, tests, v8.x

#1320 Changelog for 7.9.1
  docs/changelog.asciidoc
Labels: documentation, todo, v7.x

#1315 [DOCS] Reorganizes Introduction and Installation chapters
  docs/authentication.asciidoc
  docs/breaking-changes.asciidoc
  docs/configuration.asciidoc
  docs/helpers.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/introduction.asciidoc
  docs/observability.asciidoc
  docs/testing.asciidoc
  docs/typescript.asciidoc
  docs/usage.asciidoc
Labels: backport 7.x, documentation, v8.x

#1316 Adds [discrete] to common parameters and API titles when generating API docs
  scripts/utils/generateDocs.js
Labels: backport 7.x, documentation, v8.x

#1313 Test cloud id without kibana component
  test/unit/client.test.js
Labels: backport 7.x, tests, v8.x

#1310 Update helpers.asciidoc
  docs/helpers.asciidoc
Labels: backport master, documentation, v7.x

#1325 Skip ulong integration test test
  test/integration/index.js
Labels: backport 7.x, tests, v8.x
