Repository elastic/elasticsearch-js, pull requests merged in 2020-11, with the labels that each got.

#1342 [DOCS] Adds Connecting section to Node.JS docs
  docs/authentication.asciidoc
  docs/connecting.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/introduction.asciidoc
Labels: backport 7.x, documentation, v8.x

#1344 [7.x][DOCS] Adds Connecting section to Node.JS docs
  docs/authentication.asciidoc
  docs/connecting.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/introduction.asciidoc
  docs/redirects.asciidoc
Labels: backport 7.x, documentation

#1346 Added node.js support doc
  README.md
  docs/installation.asciidoc
Labels: backport 7.x, documentation, v8.x

#1349 Add warning log about nodejs version support
  index.js
Labels: backport 7.x, v8.x

#1343 Handle connectivity issues while reading the body
  .github/workflows/nodejs.yml
  lib/Connection.js
  lib/Transport.js
  package.json
  test/unit/client.test.js
  test/unit/connection.test.js
  test/unit/transport.test.js
  test/utils/MockConnection.js
Labels: backport 7.x, bugfix, v8.x

#1348 Changelog for 7.10
  docs/changelog.asciidoc
Labels: documentation, todo, v7.x

#1356 Updated integration test cleanup code
  test/integration/helper.js
  test/integration/test-runner.js
Labels: backport 7.x, tests, v8.x

#1355 Throw if the content length is too big
  lib/Transport.js
  test/unit/client.test.js
Labels: backport 7.x, bugfix, v8.x

#1362 [DOCS] Fixes link in API docs
  docs/reference.asciidoc
Labels: backport 7.x, documentation, v8.x
