Repository elastic/elasticsearch-js, pull requests merged in 2020-10, with the labels that each got.

#1329 Fix request typo and redeclare block-scoped variable 'response'
  docs/typescript.asciidoc
Labels: backport 7.x, documentation, v8.x

#1331 Scroll search should clear the scroll at the end
  lib/Helpers.js
  test/unit/helpers/scroll.test.js
Labels: backport 7.x, bugfix, v8.x

#1332 The agent function should take the Connection contructor options as argument
  docs/configuration.asciidoc
  lib/Connection.d.ts
  lib/Connection.js
  test/types/connection.test-d.ts
  test/unit/connection.test.js
Labels: backport 7.x, semver-minor, v8.x

#1335 Fix integration test
  test/integration/test-runner.js
Labels: backport 7.x, tests, v8.x
