Repository elastic/elasticsearch-js, pull requests merged in 2021-03, with the labels that each got.

#1413 Update usage link (#1404)
  README.md
Labels: documentation

#1417 Fix test bundler
  .gitignore
  test/bundlers/parcel-test/package.json
Labels: backport 7.x, tests, v8.x

#1407 [DOCS] Adds Integrations section to Node.JS docs
  docs/advanced-config.asciidoc
  docs/configuration.asciidoc
  docs/index.asciidoc
  docs/integrations.asciidoc
  docs/observability.asciidoc
  docs/testing.asciidoc
  docs/transport.asciidoc
  docs/typescript.asciidoc
Labels: backport 7.x, documentation, v8.x

#1419 [7.x][DOCS] Adds Integrations section to Node.JS docs
  docs/advanced-config.asciidoc
  docs/configuration.asciidoc
  docs/index.asciidoc
  docs/integrations.asciidoc
  docs/observability.asciidoc
  docs/testing.asciidoc
  docs/transport.asciidoc
  docs/typescript.asciidoc
Labels: documentation, v7.x

#1414 Disable prototype poisoning option
  docs/basic-config.asciidoc
  index.d.ts
  index.js
  lib/Helpers.js
  lib/Serializer.d.ts
  lib/Serializer.js
  test/types/client-options.test-d.ts
  test/unit/client.test.js
  test/unit/serializer.test.js
Labels: backport 7.x, semver-minor, v8.x

#1415 fix(TransportRequestPromise): add finally method to TransportRequestP…
  lib/Transport.d.ts
  lib/Transport.js
  test/unit/api.test.js
Labels: backport 7.x, bugfix, v8.x

#1421 [DOCS] Fix readme links
  README.md
Labels: backport 7.x, documentation, v8.x

#1423 Integration test: Fix yaml parser and crash on failure
  test/integration/helper.js
  test/integration/index.js
  test/integration/test-runner.js
Labels: backport 7.x, tests, v8.x

#1422 Updated changelog.asciidoc
  docs/changelog.asciidoc
Labels: documentation

#1358 New type definitions
  api/esapi.d.ts
  api/kibana.d.ts
  api/types.d.ts
  index.d.ts
  lib/Transport.d.ts
  scripts/generate.js
  scripts/utils/index.js
  test/types/api-response-body.test-d.ts
  test/types/api-response.test-d.ts
  test/types/client-options.test-d.ts
  test/types/client.test-d.ts
  test/types/kibana.test-d.ts
Labels: backport 7.x, semver-minor, todo, typescript, v8.x

#1425 [DOCS] Rearranges Examples section in Node.JS book
  docs/examples/asStream.asciidoc
  docs/examples/bulk.asciidoc
  docs/examples/exists.asciidoc
  docs/examples/get.asciidoc
  docs/examples/ignore.asciidoc
  docs/examples/index.asciidoc
  docs/examples/msearch.asciidoc
  docs/examples/reindex.asciidoc
  docs/examples/scroll.asciidoc
  docs/examples/search.asciidoc
  docs/examples/sql.query.asciidoc
  docs/examples/suggest.asciidoc
  docs/examples/transport.request.asciidoc
  docs/examples/typescript.asciidoc
  docs/examples/update.asciidoc
  docs/examples/update_by_query.asciidoc
  docs/index.asciidoc
Labels: backport 7.x, documentation, v8.x

#1431 [7.x][DOCS] Rearranges Examples section in Node.JS book (#1425)
  docs/examples/asStream.asciidoc
  docs/examples/bulk.asciidoc
  docs/examples/exists.asciidoc
  docs/examples/get.asciidoc
  docs/examples/ignore.asciidoc
  docs/examples/index.asciidoc
  docs/examples/msearch.asciidoc
  docs/examples/reindex.asciidoc
  docs/examples/scroll.asciidoc
  docs/examples/search.asciidoc
  docs/examples/sql.query.asciidoc
  docs/examples/suggest.asciidoc
  docs/examples/transport.request.asciidoc
  docs/examples/typescript.asciidoc
  docs/examples/update.asciidoc
  docs/examples/update_by_query.asciidoc
  docs/index.asciidoc
Labels: backport 7.x, documentation, v7.x

#1436 Move integration test to artifact API
  .ci/Dockerfile
  package.json
  scripts/download-artifacts.js
  test/integration/index.js
Labels: backport 7.x, tests, v8.x
