Repository elastic/elasticsearch-js, pull requests merged in 2021-05, with the labels that each got.

#1457 Improve response error message
  lib/errors.js
  test/unit/errors.test.js
Labels: backport 7.x, enhancement, v8.x

#1460 Catch HEAD errors
  lib/Transport.js
  test/unit/transport.test.js
Labels: backport 7.x, bugfix, v8.x

#1466 Updated integration test helpers
  test/integration/helper.js
Labels: backport 7.x, tests, v8.x

#1468 Add top level type error to error message
  lib/errors.js
  test/types/kibana.test-d.ts
  test/types/new-types.test-d.ts
  test/unit/errors.test.js
Labels: backport 7.x, semver-minor, v8.x

#1470 [DOCS] Removes link from API reference that breaks the docs build
  docs/reference.asciidoc
Labels: documentation, v8.x

#1472 Update body error check
  lib/errors.js
Labels: backport 7.x, semver-minor, v8.x

#1471 Drop node v10 support
  .ci/test-matrix.yml
  .github/workflows/nodejs.yml
  index.js
  lib/Connection.js
  package.json
  test/acceptance/events-order.test.js
  test/acceptance/observability.test.js
  test/acceptance/proxy.test.js
  test/acceptance/resurrect.test.js
  test/acceptance/sniff.test.js
  test/integration/helpers/bulk.test.js
  test/integration/helpers/msearch.test.js
  test/integration/helpers/scroll.test.js
  test/integration/helpers/search.test.js
  test/integration/test-runner.js
  test/unit/api-async.js
  test/unit/api.test.js
  test/unit/base-connection-pool.test.js
  test/unit/child.test.js
  test/unit/client.test.js
  test/unit/cloud-connection-pool.test.js
  test/unit/connection-pool.test.js
  test/unit/connection.test.js
  test/unit/errors.test.js
  test/unit/esm/index.mjs
  test/unit/events.test.js
  test/unit/helpers/bulk.test.js
  test/unit/helpers/msearch.test.js
  test/unit/helpers/scroll.test.js
  test/unit/helpers/search.test.js
  test/unit/selectors.test.js
  test/unit/serializer.test.js
  test/unit/transport.test.js
Labels: backport 7.x, semver-minor, v8.x

#1476 Changelog for 7.13
  docs/changelog.asciidoc
Labels: documentation, v7.x
