Repository elastic/elasticsearch-js, pull requests merged in 2021-02, with the labels that each got.

#1391 [DOCS] Adds Configuration section to Node.JS docs
  docs/advanced-config.asciidoc
  docs/basic-config.asciidoc
  docs/child.asciidoc
  docs/configuration.asciidoc
  docs/extend.asciidoc
  docs/index.asciidoc
Labels: documentation, v7.x, v8.x

#1396 [7.x][DOCS] Adds Configuration section to Node.JS docs
  docs/advanced-config.asciidoc
  docs/basic-config.asciidoc
  docs/child.asciidoc
  docs/configuration.asciidoc
  docs/extend.asciidoc
  docs/index.asciidoc
Labels: backport 7.x, documentation, v7.x

#1398 Added Elasticsearch proxy example
  README.md
  docs/examples/proxy/.gitignore
  docs/examples/proxy/README.md
  docs/examples/proxy/api/autocomplete.js
  docs/examples/proxy/api/delete.js
  docs/examples/proxy/api/index.js
  docs/examples/proxy/api/search.js
  docs/examples/proxy/package.json
  docs/examples/proxy/utils/authorize.js
  docs/examples/proxy/utils/prepare-elasticsearch.js
  docs/examples/proxy/vercel.json
  docs/installation.asciidoc
Labels: documentation

#1399 Fix CI
  .ci/run-repository.sh
  test/integration/index.js
Labels: tests

#1401 Changelog for 7.11
  docs/changelog.asciidoc
Labels: documentation, v7.x

#1400 [helpers] add support for transport options to all helpers
  lib/Helpers.d.ts
  lib/Helpers.js
  test/unit/helpers/bulk.test.js
  test/unit/helpers/msearch.test.js
Labels: backport 7.x, semver-minor, v8.x

#1402 Remove Node.js v8 support
  .ci/test-matrix.yml
  .github/workflows/nodejs.yml
  README.md
  api/utils.js
  docs/examples/asStream.asciidoc
  docs/examples/scroll.asciidoc
  docs/examples/sql.query.asciidoc
  docs/installation.asciidoc
  index.js
  lib/Connection.js
  lib/Serializer.js
  lib/Transport.js
  lib/pool/BaseConnectionPool.js
  lib/pool/ConnectionPool.js
  package.json
  scripts/generate-docs-examples.js
  scripts/utils/clone-es.js
  scripts/utils/generateApis.js
  scripts/utils/generateDocs.js
  scripts/utils/generateMain.js
  scripts/utils/generateRequestTypes.js
  test/acceptance/observability.test.js
  test/acceptance/resurrect.test.js
  test/acceptance/sniff.test.js
  test/benchmarks/macro/complex.bench.js
  test/benchmarks/macro/simple.bench.js
  test/benchmarks/micro/basic.bench.js
  test/benchmarks/suite.js
  test/integration/helpers/scroll.test.js
  test/integration/index.js
  test/integration/test-runner.js
  test/unit/base-connection-pool.test.js
  test/unit/child.test.js
  test/unit/client.test.js
  test/unit/connection-pool.test.js
  test/unit/connection.test.js
  test/unit/events.test.js
  test/unit/helpers/bulk.test.js
  test/unit/helpers/scroll.test.js
  test/unit/selectors.test.js
  test/unit/transport.test.js
  test/utils/MockConnection.js
  test/utils/buildCluster.js
  test/utils/buildServer.js
Labels: backport 7.x, semver-minor, v8.x
