Repository elastic/elasticsearch-js, pull requests merged in 2021-04, with the labels that each got.

#1438 Updated integration test cleanup
  .ci/run-elasticsearch.sh
  scripts/es-docker-platinum.sh
  scripts/es-docker.sh
Labels: tests, v8.x

#1441 Updated code generation
  scripts/utils/generateApis.js
  scripts/utils/generateMain.js
  scripts/utils/generateRequestTypes.js
Labels: backport 7.x, v8.x

#1444 Wrap inside array ndjson bodies in integration test
  test/integration/test-runner.js
Labels: backport 7.x, tests, v8.x

#1446 Updated new types export
  api/new.d.ts
  docs/typescript.asciidoc
  test/types/new-types.test-d.ts
Labels: backport 7.x, typescript, v8.x

#1454 [7.x][DOCS] Renames Changelog to Release notes in Node.JS book.
  docs/breaking-changes.asciidoc
  docs/changelog.asciidoc
  docs/index.asciidoc
  docs/introduction.asciidoc
Labels: documentation, v7.x

#1453 [DOCS] Adds Breaking changes from old client to Introduction
  docs/breaking-changes.asciidoc
  docs/index.asciidoc
  docs/introduction.asciidoc
Labels: documentation, v8.x

#1434 [DOCS] Reviews Client helpers section in the Node.JS book
  docs/helpers.asciidoc
Labels: documentation, v7.x, v8.x

#1458 [7.x][DOCS] Reviews Client helpers section in the Node.JS book
  docs/helpers.asciidoc
Labels: backport 7.x, documentation, v7.x
