Repository elastic/elasticsearch-js, pull requests merged in 2021-09, with the labels that each got.

#1546 [DOCS] Adds a link to the Quick Start section that points to an EC ingest example
  docs/introduction.asciidoc
Labels: documentation, v8.x, backport 7.x

#1551 Add support for maxResponseSize and maxCompressedResponseSize
  docs/basic-config.asciidoc
  docs/connecting.asciidoc
  index.d.ts
  index.js
  lib/Transport.d.ts
  lib/Transport.js
  test/unit/client.test.js
Labels: semver-minor, v8.x, backport 7.x

#1550 Update compatibility info
  README.md
  docs/installation.asciidoc
Labels: documentation, v8.x, backport 7.x

#1555 Show socket local/remote address in case of ECONNRESET
  lib/Connection.js
  test/unit/connection.test.js
Labels: semver-minor, v8.x, backport 7.x

#1557 Changelog for 7.15
  docs/changelog.asciidoc
Labels: documentation, v7.x
