Repository elastic/elasticsearch-js, pull requests merged in 2021-07, with the labels that each got.

#1428 Bulk update improvements
  lib/Helpers.d.ts
  lib/Helpers.js
  test/unit/helpers/bulk.test.js
Labels: backport 7.x, semver-minor, v8.x

#1488 Add support for bearer auth
  docs/basic-config.asciidoc
  docs/connecting.asciidoc
  index.d.ts
  lib/Connection.js
  lib/pool/index.d.ts
  test/unit/client.test.js
Labels: backport 7.x, semver-minor, v8.x

#1478 Add api compatibility header support
  docs/advanced-config.asciidoc
  index.js
  lib/Transport.js
  test/unit/client.test.js
Labels: backport 7.x, internals, v8.x

#1493 Update integration test
  .ci/run-elasticsearch.sh
  test/integration/index.js
  test/integration/test-runner.js
Labels: backport 7.x, tests, v8.x

#1487 Verify connection to Elasticsearch
  docs/connecting.asciidoc
  index.js
  lib/Transport.d.ts
  lib/Transport.js
  lib/errors.d.ts
  lib/errors.js
  test/acceptance/events-order.test.js
  test/acceptance/observability.test.js
  test/acceptance/product-check.test.js
  test/acceptance/proxy.test.js
  test/acceptance/resurrect.test.js
  test/acceptance/sniff.test.js
  test/unit/api-async.js
  test/unit/api.test.js
  test/unit/child.test.js
  test/unit/client.test.js
  test/unit/events.test.js
  test/unit/helpers/bulk.test.js
  test/unit/helpers/msearch.test.js
  test/unit/helpers/scroll.test.js
  test/unit/helpers/search.test.js
  test/unit/transport.test.js
  test/utils/MockConnection.js
  test/utils/index.js
Labels: backport 7.x, semver-minor, v8.x

#1501 Do not check for 100% coverage in coverage report
  .github/workflows/nodejs.yml
  package.json
Labels: backport 7.x, tests, v8.x

#1498 Better message in case of unsupported build flavor
  README.md
  docs/installation.asciidoc
  lib/Transport.js
  test/acceptance/product-check.test.js
Labels: backport 7.x, enhancement, v8.x

#1503 Add note about prototype poisoning protection perf
  docs/basic-config.asciidoc
Labels: backport 7.x, documentation, v8.x
