Repository elastic/elasticsearch-js, pull requests merged in 2022-03, with the labels that each got.

#1647 Update v8 changelog
  docs/changelog.asciidoc
Labels: documentation, bugfix, backport 8.0, backport 8.1

#1646 Update API reference for v8
  docs/reference.asciidoc
Labels: documentation, v8.x, backport 8.0, backport 8.1

#1648 Export SniffingTransport
  index.d.ts
  index.js
Labels: semver-minor, backport 8.1

#1654 [DOCS] Add discrete tags to API ref
  docs/reference.asciidoc
Labels: v8.x, backport 8.0, backport 8.1

#1655 [8.1] [DOCS] Add discrete tags to API ref (#1654)
  docs/reference.asciidoc
Labels: backport

#1657 Changelog for 8.1
  docs/changelog.asciidoc
Labels: documentation, backport 8.1

#1666 Update connecting documentation
  README.md
  docs/advanced-config.asciidoc
  docs/basic-config.asciidoc
  docs/child.asciidoc
  docs/connecting.asciidoc
  docs/examples/asStream.asciidoc
  docs/examples/bulk.asciidoc
  docs/examples/exists.asciidoc
  docs/examples/get.asciidoc
  docs/examples/ignore.asciidoc
  docs/examples/msearch.asciidoc
  docs/examples/reindex.asciidoc
  docs/examples/scroll.asciidoc
  docs/examples/search.asciidoc
  docs/examples/sql.query.asciidoc
  docs/examples/suggest.asciidoc
  docs/examples/transport.request.asciidoc
  docs/examples/update.asciidoc
  docs/examples/update_by_query.asciidoc
  docs/helpers.asciidoc
  docs/introduction.asciidoc
  docs/observability.asciidoc
  docs/testing.asciidoc
  docs/transport.asciidoc
  docs/typescript.asciidoc
Labels: documentation, backport 8.0, backport 8.1

#1670 Drop Node.js v12
  .ci/packer_cache.sh
  .ci/run-repository.sh
  .ci/test-matrix.yml
  .github/workflows/nodejs.yml
  README.md
  docs/installation.asciidoc
  package.json
Labels: backport 8.2
