Repository elastic/elasticsearch-js, pull requests merged in 2022-02, with the labels that each got.

#1572 Update docs for v8
  README.md
  docs/advanced-config.asciidoc
  docs/basic-config.asciidoc
  docs/breaking-changes.asciidoc
  docs/child.asciidoc
  docs/configuration.asciidoc
  docs/connecting.asciidoc
  docs/examples/asStream.asciidoc
  docs/examples/bulk.asciidoc
  docs/examples/exists.asciidoc
  docs/examples/get.asciidoc
  docs/examples/ignore.asciidoc
  docs/examples/index.asciidoc
  docs/examples/msearch.asciidoc
  docs/examples/proxy/api/autocomplete.js
  docs/examples/proxy/api/delete.js
  docs/examples/proxy/api/index.js
  docs/examples/proxy/api/search.js
  docs/examples/proxy/package.json
  docs/examples/proxy/utils/prepare-elasticsearch.js
  docs/examples/reindex.asciidoc
  docs/examples/scroll.asciidoc
  docs/examples/search.asciidoc
  docs/examples/sql.query.asciidoc
  docs/examples/suggest.asciidoc
  docs/examples/transport.request.asciidoc
  docs/examples/typescript.asciidoc
  docs/examples/update.asciidoc
  docs/examples/update_by_query.asciidoc
  docs/extend.asciidoc
  docs/helpers.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/introduction.asciidoc
  docs/observability.asciidoc
  docs/testing.asciidoc
  docs/typescript.asciidoc
Labels: documentation, v8.x, backport 8.0, backport 8.1

#1629 Bump transport version
  package.json
Labels: bugfix, backport 8.0, backport 8.1

#1616 Fix onFlushTimeout timer not being cleared when upstream errors
  src/helpers.ts
Labels: bugfix, backport 8.1

#1633 Remove custom kibana interface
  .npmignore
  scripts/release-canary.js
  src/api/kibana.ts
  src/api/types.ts
  src/api/typesWithBodyKey.ts
  src/helpers.ts
Labels: internals

#1628 docs: fix typo
  docs/typescript.asciidoc
Labels: documentation

#1540 [DOCS] Fix double backticks for inline code snippets
  docs/advanced-config.asciidoc
Labels: documentation

#1609 docs: typo
  docs/helpers.asciidoc
Labels: documentation

#1634 [DOCS] Add redirects for authentication and migration guide
  docs/basic-config.asciidoc
  docs/connecting.asciidoc
  docs/index.asciidoc
  docs/redirects.asciidoc
Labels: documentation, v8.x, backport 8.0, backport 8.1

#1640 [8.1] [DOCS] Add redirects for authentication and migration guide (#1634)
  docs/basic-config.asciidoc
  docs/connecting.asciidoc
  docs/index.asciidoc
  docs/redirects.asciidoc
Labels: backport 8.1, backport
