Repository elastic/elasticsearch-js, pull requests merged in 2024-11, with the labels that each got.

#2407 Add streaming support to Arrow helper
  docs/changelog.asciidoc
  docs/connecting.asciidoc
  docs/helpers.asciidoc
  docs/transport.asciidoc
  package.json
  src/helpers.ts
  test/unit/helpers/esql.test.ts
Labels: backport 8.x, backport 8.16

#2432 Add `_id` to the result of `helpers.search`
  src/helpers.ts
  test/unit/helpers/search.test.ts
Labels: backport 8.x, backport 8.16

#2444 Add changelog for 8.15.2
  docs/changelog.asciidoc
Labels: backport 8.x, backport 8.16

#2460 Upgrade ts-standard
  package.json
  src/helpers.ts
Labels: backport 8.x, backport 8.16

#2475 Fix ECMAScript import
  .github/workflows/nodejs.yml
  package.json
  test/esm/package.json
  test/esm/test-import.mjs
Labels: backport 8.x, backport 8.16

#2479 Add changelog for 8.16.1
  docs/changelog.asciidoc
Labels: backport 8.x

#2484 Add docstrings for Client class and related properties
  src/client.ts
Labels: backport 8.x, backport 8.17

#2487 Ignore tap artifacts
  .dockerignore
  .gitignore
  .npmignore
Labels: backport 8.15, backport 8.x, backport 8.16, backport 8.17

#2490 Update changelog to include 8.16.2 and 8.15.3
  docs/changelog.asciidoc
Labels: backport 8.x, backport 8.17
