Repository elastic/elasticsearch-js, pull requests merged in 2024-04, with the labels that each got.

#2202 Upgrade transport to 8.5.0
  package.json
Labels: backport 8.14

#2199 onSuccess function for bulk helper
  docs/changelog.asciidoc
  docs/helpers.asciidoc
  src/helpers.ts
  test/unit/helpers/bulk.test.ts
Labels: backport 8.14

#2218 Backport changelogs from other minor releases
  docs/changelog.asciidoc
Labels: backport 8.14

#2208 Add `Date` to `DateMath` type
  src/api/types.ts
  src/api/typesWithBodyKey.ts
Labels: Area: Specification, Category: Enhancement

#2236 Move make.sh to .github
  .github/make.sh
Labels: backport 8.13, backport 8.14

#2242 Update asStream code example
  docs/examples/asStream.asciidoc
Labels: backport 8.13, backport 8.14
