Repository elastic/elasticsearch-js, pull requests merged in 2025-05, with the labels that each got.

#2822 Export helper types
  index.d.ts
Labels: backport 8.19, backport 8.18, backport 9.0

#2821 Remove dangling references to typesWithBodyKey
  docs/reference/typescript.md
  index.d.ts
Labels: backport 9.0

#2836 [docs] Add `products` to `docset.yml`
  docs/docset.yml
Labels: Area: Documentation

#2839 Mention typesWithBody in breaking changes
  docs/release-notes/breaking-changes.md
Labels: backport 9.0

#2843 Bump to 9.0.2
  docs/release-notes/index.md
  package.json
Labels: backport 9.0
