Repository elastic/elasticsearch-js, pull requests merged in 2025-03, with the labels that each got.

#2640 [docs] Clean up cross-repo links
  docs/docset.yml
  docs/reference/api-reference.md
  docs/reference/connecting.md
  docs/reference/observability.md
Labels: Area: Documentation

#2649 [docs] Fix external links
  docs/reference/connecting.md
Labels: Area: Documentation

#2664 Assume codegen renders markdown, not asciidoc
  .buildkite/make.mjs
Labels: backport 9.0

#2667 SPDX license format
  .buildkite/make.mjs
  .github/workflows/nodejs.yml
  docs/examples/proxy/api/autocomplete.js
  docs/examples/proxy/api/delete.js
  docs/examples/proxy/api/index.js
  docs/examples/proxy/api/search.js
  docs/examples/proxy/utils/authorize.js
  docs/examples/proxy/utils/prepare-elasticsearch.js
  index.d.ts
  index.js
  package.json
  scripts/check-spdx
  scripts/download-artifacts.js
  scripts/generate-docs-examples.js
  scripts/generate.js
  scripts/kibana-docker.sh
  scripts/release-canary.js
  scripts/utils/clone-es.js
  scripts/utils/generateApis.js
  scripts/utils/generateDocs.js
  scripts/utils/generateMain.js
  scripts/utils/generateRequestTypes.js
  scripts/utils/index.js
  scripts/utils/patch.json
  scripts/wait-cluster.sh
  src/client.ts
  src/helpers.ts
  src/sniffingTransport.ts
  test/esm/test-import.mjs
  test/integration/helper.js
  test/integration/helpers/bulk.test.js
  test/integration/helpers/msearch.test.js
  test/integration/helpers/scroll.test.js
  test/integration/helpers/search.test.js
  test/integration/index.js
  test/integration/reporter.js
  test/integration/test-runner.js
  test/mock/index.js
  test/unit/api.test.ts
  test/unit/client.test.ts
  test/unit/helpers/bulk.test.ts
  test/unit/helpers/esql.test.ts
  test/unit/helpers/msearch.test.ts
  test/unit/helpers/scroll.test.ts
  test/unit/helpers/search.test.ts
  test/utils/MockConnection.ts
  test/utils/buildCluster.ts
  test/utils/buildProxy.ts
  test/utils/buildServer.ts
  test/utils/index.ts
Labels: backport 9.0

#2663 [docs] Miscellaneous docs clean up
  docs/docset.yml
  docs/reference/getting-started.md
  docs/reference/images/create-api-key.png
  docs/reference/images/es-endpoint.jpg
Labels: Area: Documentation

#2665 Updates navigation titles and descriptions for release notes
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: Area: Documentation

#2674 Drop broken support for roles
  docs/basic-config.asciidoc
  src/client.ts
Labels: backport 8.18

#2684 [docs] Add missing mapped pages
  docs/release-notes/index.md
Labels: Area: Documentation
