Repository elastic/elasticsearch-js, pull requests merged in 2025-04, with the labels that each got.

#2685 [Docs] Replace mis-converted table
  docs/reference/basic-config.md
Labels: Area: Documentation, backport 9.0

#2695 Merge serverless functionality from @elastic/elasticsearch-serverless
  docs/reference/basic-config.md
  docs/reference/client-helpers.md
  docs/reference/configuration.md
  docs/reference/connecting.md
  src/client.ts
  test/unit/client.test.ts
Labels: backport 9.0

#2697 Update helpers to use new multisearch types
  .buildkite/Dockerfile
  .buildkite/Dockerfile-make
  src/helpers.ts
Labels: backport 9.0

#2702 Bump to 8.18.0
  package.json
Labels: backport 8.18

#2712 Changelog for 9.0.0
  docs/release-notes/breaking-changes.md
  docs/release-notes/index.md
Labels: backport 9.0

#2727 [Docs] Restore timeout best practices
  docs/reference/timeout-best-practices.md
  docs/reference/toc.yml
Labels: Area: Documentation, backport 9.0

#2729 Fix link to timeout best practices
  docs/reference/configuration.md
Labels: Area: Documentation, backport 9.0

#2738 Update ESQL helper types
  src/helpers.ts
Labels: backport 9.0

#2731 Bug #2694
  src/client.ts
  test/unit/client.test.ts
Labels: backport 8.x, backport 8.18, backport 9.0

#2745 Update changelog to include fix for #2694
  docs/release-notes/index.md
Labels: backport 9.0

#2746 Add changelog for 8.18
  docs/changelog.asciidoc
Labels: backport 8.18

#2749 Bump version to 9.0.0
  package.json
Labels: backport 9.0

#2753 [docs] Fix image paths for docs-assembler
  docs/reference/getting-started.md
Labels: Area: Documentation, backport 9.0

#2756 Add test to verify default node filter function
  docs/reference/basic-config.md
  package.json
  src/client.ts
  test/unit/client.test.ts
Labels: backport 8.x

#2757 Bump transport to latest 8.x version
  package.json
Labels: backport 8.18

#2760 Bump to 8.18.1
  package.json
Labels: backport 8.18

#2766 Improve deserialization docs
  docs/observability.asciidoc
Labels: backport 8.18

#2763 Add release notes for 8.18.1
  docs/changelog.asciidoc
Labels: backport 8.18

#2750 Migrate integration tests to built JS files
  .buildkite/pipeline.yml
  .buildkite/run-client.sh
  .dockerignore
  .gitignore
  .npmignore
  package.json
  scripts/download-artifacts.js
  scripts/generate-docs-examples.js
  test/integration/index.js
  test/integration/reporter.js
  test/integration/test-builder.js
  test/integration/test-runner.js
Labels: backport 8.x, backport 8.18, backport 9.0

#2788 Use async reader for parsing Apache Arrow responses
  docs/reference/client-helpers.md
  src/helpers.ts
  test/unit/helpers/esql.test.ts
Labels: backport 8.x, backport 8.18, backport 9.0

#2793 8.18.2 changelog
  docs/changelog.asciidoc
Labels: backport 8.18

#2795 Bump to 8.18.2
  package.json
Labels: backport 8.18

#2797 Bump to 9.0.1
  package.json
Labels: backport 9.0
